# Generated by Django 4.2.1 on 2023-05-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_file_section_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_section',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='coding.section_type'),
        ),
    ]
